name: Fetch Historical Gold Prices (Récupérer les prix historiques de l'or)

on:
  schedule:
    # Exécuter tous les jours à minuit UTC
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  fetch-gold-prices:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository (Vérifier le dépôt)
      uses: actions/checkout@v2

    - name: Set up Python (Configurer Python)
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies (Installer les dépendances)
      run: pip install yfinance pandas

    - name: Run script to fetch historical gold prices (Exécuter le script pour récupérer les prix historiques de l'or)
      run: python historical_gold_prices.py

    - name: Commit CSV files (Committer les fichiers CSV)
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add gold_monthly_data.csv gold_weekly_data.csv gold_daily_data.csv
        git commit -m 'Update historical gold prices data'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
